import { AuthProvider } from "../components/AuthProvider";
import { Navbar } from "../components/Navbar";
import { ApolloWrapper } from "../lib/apolloWrapper";
import "../styles/globals.css";
import { BagContextProvider } from "./context/bagContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://rsms.me/inter/inter.css"
          as="style"
        />
      </head>
      <body className="font-sans">
        <ApolloWrapper>
          <AuthProvider>
            <BagContextProvider>
              <Navbar />
              <main>{children}</main>
            </BagContextProvider>
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
