import { GetProductQuery } from "../generated/graphql/graphql";
import { ApolloWrapper } from "../lib/apolloWrapper";
import "../styles/globals.css";
import { getProducts } from "./api/queries";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://rsms.me/inter/inter.css"
          as="style"
        />
      </head>
      <body className="font-sans">
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
